### ISSUE TITLE
Crash on Android when calling `itemKey` with no arguments

### ISSUE THREAD

**Issue by sproctor** [cashapp/multiplatform-paging#115]
I'm not sure if this is a bug from the AndroidX library. It only happens when calling `itemKey` with no arguments.

```
java.lang.IllegalArgumentException: Type of the key PagingPlaceholderKey(index=0) is not supported. On Android you can only use types which can be stored inside the Bundle.
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:78)
```

**Comment by sproctor** [comment]
This happens when using `app.cash.paging:paging-compose-common:3.2.0-alpha05-0.2.2`

**Comment by veyndan** [comment]
Thanks for the report! I managed to reproduce it on my end and it seems to be related to Multiplatform Paging.

It looks like depending on `app.cash.paging:paging-compose-common:3.2.0-alpha05-0.2.2` on Android pulls in the JVM version of the library instead of the Android version. I'll try and push a release a fix with this change in the next couple of days.

**Comment by sproctor** [comment]
Any news on this? Even when setting a key, I'm getting an occasional crash. I guess there's a race condition where occasionally the `PagingPlaceholderKey` is used.

**Comment by veyndan** [comment]
Apologies for the delay. The android target wasn't being published. Fixed it in https://github.com/cashapp/multiplatform-paging/commit/5e4c4bfb6be51e07496b02ffdfd80295b584cbea and [just released a fix now](https://github.com/cashapp/multiplatform-paging/releases/tag/3.2.0-alpha05-0.2.3). It should be available within a couple of hours on Maven Central.
