### ISSUE TITLE
Unresolved reference: LoadState

### ISSUE THREAD

**Issue by kodeplateform** [cashapp/multiplatform-paging#122]
Hello even with imports: 

import app.cash.paging.LoadState
import app.cash.paging.LoadState.*

LoadState.Loading ,  LoadState.Error  and LoadState.NotLoading  seems missing , would be veryuseful to be able to use it in multiplateform too

**Comment by JakeWharton** [comment]
Please check out https://github.com/cashapp/multiplatform-paging/tree/main/paging-common#nested-classes-have-been-made-top-level-classes for why these are missing and the workaround for how to use them in a multiplatform context.

**Comment by kodeplateform** [comment]
Thanks for your answer , I missed that part of the doc. Just one more question is it normal  this works :

`val loadState = LoadStateLoading as LoadState` 


but not this : 
```
val loadState0 = LoadStateError as LoadState
val loadState1 = LoadStateNotLoading as LoadState
```
  
Thanks

**Comment by veyndan** [comment]
Nope, that's not normal. What's the error message you're getting after running `./gradlew build`?

**Comment by kodeplateform** [comment]
On ide  error warning :  

`Classifier 'LoadStateNotLoading' does not have a companion object, and thus must be initialized here`

and compilation error: 

` Cannot access 'Companion': it is internal in 'NotLoading'`

**Comment by veyndan** [comment]
Apologies, I didn't read your question correctly.

What you are describing is expected. You're referencing all three classes (`LoadStateNotLoading`, `LoadStateLoading`, and `LoadStateError`) as if they are objects. Only `LoadStateLoading` is an object, which is why that passed for you. You'll need to instantiate `LoadStateNotLoading` with a value (e.g., `LoadStateNotLoading(false)`). Same deal with `LoadStateError`. This is all standard AndroidX Paging stuff (i.e., not specific to Multiplatform Paging).

**Comment by kodeplateform** [comment]
ok thank you
