### ISSUE TITLE
Js browser target: Unresolved reference: InvalidatingPagingSourceFactory

### ISSUE THREAD

**Issue by lumstep** [cashapp/multiplatform-paging#204]
Affected platforms: Browser

Versions: multiplatform-paging: 3.3.0-alpha02-0.4.0

Impossible to build project using InvalidatingPagingSourceFactory only on js.

Build exception:
Unresolved reference: InvalidatingPagingSourceFactory

**Comment by veyndan** [comment]
Unfortunately, `PagingSourceFactory` (nor its descendants like `InvalidatingPagingSourceFactory`) can be used in JS due to a constraint of Kotlin/JS. According to the compiler, "Implementing function interface is prohibited in JavaScript", so unfortunately we just have to make do without it until Kotlin/JS lifts this constraint.
